### ISSUE TITLE
Import Scales and Chords

### ISSUE THREAD

**Issue by lvm** [munshkr/vim-tidal#10]
TidalCycles 0.9 contains scales and chords which perphaps could to be added in the startup file by calling these two imports:
```haskell
import qualified Sound.Tidal.Scales as Scales
import qualified Sound.Tidal.Chords as Chords
```

**Comment by munshkr** [comment]
Thanks! I added them in branch 0.9-dev, mimicking the branches on Tidal and SuperDirt.
