### ISSUE TITLE
Tidal 0.9.1 / 0.9.2 support

### ISSUE THREAD

**Issue by jdmnd** [munshkr/vim-tidal#15]
It appears that in Tidal 0.9.1/[0.9.2](http://hackage.haskell.org/package/tidal-0.9.2/docs/Sound-Tidal-Pattern.html#v:-126--62-)
```hs
(~>) :: Time -> Pattern a -> Pattern a
```
changed to 
```hs
(~>) :: Pattern Time -> Pattern a -> Pattern a
```

which breaks the definition of `retrig`:
https://github.com/munshkr/vim-tidal/blob/master/ftplugin/tidal.vim#L9

**Comment by munshkr** [comment]
Thanks! I updated both the bootstrap code and the current position bindings. Do you mind checking if it works for you now?

**Comment by jdmnd** [comment]
That seems to have worked great. Thanks a lot! :)

**Comment by munshkr** [comment]
:metal:
