### ISSUE TITLE
Mac 10.12.16: tidalvim/tidal doesn't connect to supercollider

### ISSUE THREAD

**Issue by chrisbeckstrom** [munshkr/vim-tidal#18]
Been troubleshooting this all morning, maybe I'm just missing something. 

SuperDirt is "listening on port 57120"

If I run `tidalvim`, I get what I expect to see (2 tmux panes, vim on top and the interpreter (I think that's what it's called) on the bottom.

After about 60 seconds, I get a bunch of errors in the lower tmux pane.

`... Failed to connect to tidal server. Try specifying a different port (default is 9160) setting the environment variable TIDAL_TEMPO_PORT`

So I read and re-read the readme, and tried these things:

- In `/usr/local/bin/tidal` and `/usr/local/bin/tidalvim` I tried adding `TIDAL_TEMPO_PORT=57120` to the command string (after where it already says `TIDAL_BOOT_PATH=$TIDAL_BOOT_PATH`etc.

- tried changing supercollider/superdirt's port to 9160, but after I did that it failed to load the server with no explanation (except `RESULT=1`)

- in the command prompt, tried running `TIDAL_TEMPO_PORT=57120` and then running `tidal` and `tidalvim`, same results 

- in the command prompt, tried running `TIDAL_TEMPO_PORT=57120 tidal`, same results

I would be grateful if anybody could help me out here... I feel like I'm close and just missing some important detail! thanks in advance

**Comment by munshkr** [comment]
Sorry about the delayed reply! I don't know if you managed to solve the problem or not, but it seems to me that there's something wrong with your Tidal installation. Just to clarify about the error message:

`... Failed to connect to tidal server. Try specifying a different port (default is 9160) setting the environment variable TIDAL_TEMPO_PORT` is a message from Tidal. 9160 is the port it uses for its internal clock. The 57120 you see when you start SuperDirt is the one that Tidal and SuperCollider use to communicate with each other, so it's a separate thing.

Can you try using another editor? If the error still happens, I suggest you ask in the #tidal channel on the Livecoding Slack.

**Comment by chrisbeckstrom** [comment]
Sorry for the delay! I reinstalled tidalvim and it looks like it can connect. The "c-e" evaluate shortcut isn't working, but I'm getting there! Thanks for your help
