### ISSUE TITLE
How to comment?

### ISSUE THREAD

**Issue by gilfuser** [munshkr/vim-tidal#20]
Hi.
When using Tidal in Atom I use comments to 'turn off' lines of code live. Is there a way to do it with tidalvim?
I tried " and // but it didn't work.

thanks

bests,
Gil

**Comment by munshkr** [comment]
There's no binding for commenting lines, but you can write `--` at the beginning of the line to comment it (that's the Haskell way).

I haven't tried it but there are plugins that provide a way to comment lines or multiple lines and bind those commands, like [NERD Commenter](https://github.com/scrooloose/nerdcommenter).

**Comment by mahsadarabi66** [comment]
Perfect :)
 [دانلود آهنگ](https://naslemusic.com)
[رضا صادقی](https://naslemusic.com/tag/دانلود-جدیدترین-آهنگ-رضا-صادقی)
 [بهنام بانی عاشقم کرده](https://naslemusic.com/دانلود-آهنگ-جدید-بهنام-بانی-عاشقم-کرده.html)
