### ISSUE TITLE
<localleader>?

### ISSUE THREAD

**Issue by hughrawlinson** [munshkr/vim-tidal#6]
Would you mind clarifying in the readme what <localleader> is for vim n00bs? Or linking to an explanation or something? I've not found Google very helpful on the matter, so I've not been able to livecode in tidalvim. I'd imagine people who are as unfamiliar with vim as I am would find it very useful.

Thanks!

**Comment by munshkr** [comment]
Hi! you're right, it was poorly explained.
I've just added something about local leaders on the README file. Hopefully it's clearer now.
Also, there's more info if you type `:help leader` or `:help localleader` inside Vim.

Thank you!

**Comment by hughrawlinson** [comment]
Got it! :D It turns out my issue was a combination of things including <leader>ss mapped to stripWhitespace in my vimrc, and some weird issues with plugin conflicts that I didn't really understand. It kind of suddenly started working, which was handy.

One other suggestion I'd have is if there was a way to close everything at once - the dirt instance, the tidal prompt and vim so that it felt more like a cohesive program (which obviously I realise it's not). 

Thanks for your help!

**Comment by munshkr** [comment]
> One other suggestion I'd have is if there was a way to close everything at once - the dirt instance, the tidal prompt and vim so that it felt more like a cohesive program (which obviously I realise it's not).

Yeah, it's a pity you can't have a buffer for REPLs inside Vim (at least I couldn't find an easy way to do it), so using tmux or screen for communication was the best method I found.

You can detach from a tmux session with `c-b a` (that is "tmux prefix key + a", ctrl+b is the default). Running `tidalvim` again will open your session just as you left it. You can also kill the sesssion with `c-b :` and typing `kill-session`.
