### ISSUE TITLE
<localleader>ss doesn't send whole paragraphs into tidal interpreter

### ISSUE THREAD

**Issue by K0F** [munshkr/vim-tidal#8]
The suggested shortcut `vip` in vim selects the paragraph well, then there is a possibility to send it into interpreter by doing `<localleader>ss` ..it is quite crampy for everyday use and even livecoding practice.

If I understand it well it should detect the block by `<localleader>ss` naturally, right? It doesn't throw any error, just nothing happens when casted.

I am using spaces instad of TABs, could it be the cause?

my version of VIM is Vi IMproved 7.4 (2013 Aug 10)

thanks

**Comment by munshkr** [comment]
Sorry for the late response. If you are in visual mode, pressing `<localleader>s` should be sufficient to send it to Tidal. Are you sure you set a local leader mapping in your .vimrc file? I think by default Vim doesn't set any.
